#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	set sysmonitor.sysmonitor.enable=0
	set commit sysmonitor
}
start()
{
	[ $(ps |grep ttyd|grep -v grep|wc -l) == 0 ] && /usr/bin/ttyd -6 /bin/login &	
	if [ $(uci get sysmonitor.sysmonitor.bbr) == 1 ];  then
		sysctl -w net.ipv4.tcp_congestion_control=bbr
	else
		sysctl -w net.ipv4.tcp_congestion_control=cubic
	fi
	if [ -f "/etc/init.d/smartdns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.smartdnsAD) == 1 ];  then
			sed -i s/".*$conf-file.*$"/"conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf"/ /etc/smartdns/custom.conf
		else
			sed -i s/".*$conf-file.*$"/"#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf"/ /etc/smartdns/custom.conf	
		fi
	fi
	if [ -f "/etc/init.d/ddns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.ddns) == 1 ];  then
			/etc/init.d/ddns enable
			if [ $(ps |grep ddns|grep -v grep|wc -l) == 0 ]; then
				/etc/init.d/ddns start
			else
				/etc/init.d/ddns restart
			fi
		else
			/etc/init.d/ddns disable
			/etc/init.d/ddns stop
		fi
	fi
	$APP_PATH/sysapp.sh getip
	set sysmonitor.sysmonitor.enable=1
	set commit sysmonitor
	$APP_PATH/sysmonitor.sh &
#	touch /tmp/smartdns.patch
}


